### ISSUE TITLE
Null reference exception in CaptureSagaStateBehavior

### ISSUE THREAD

**Issue by jblackburn21** [SimonCropp/NServiceBus.Serilog#11]
Hi,

Thank you for the library.  We're running into an issue with NServiceBus.Serilog.Tracing where we get a null reference exception when a Timeout message is received for a saga that no longer exists.

In the class CaptureSagaStateBehavior

On line 81:

`sagaAudit.SagaId = saga.Entity.Id;`

The saga Entity can be null when the Data record no longer exists.

Should the audit just be ignored in this scenario?  For now we have just disabled the SagaTracing feature.

**Comment by SimonCropp** [comment]
thanks for the issue. yes u r correct the timeout for a completed saga should be ignored. I have pushed a new version to nuget with that change

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
