### ISSUE TITLE
Argument null exception?

### ISSUE THREAD

**Issue by dasjestyr** [SimonCropp/NServiceBus.Serilog#12]
NServiceBus:  6.3.4
NserviceBus.Serilog: 3.0.3
NServiceBus.Serilog.Tracing 3.0.3
Serilog: 2.5.0

I started getting this error as of late and it's preventing an endpoint from working. The strangest part is that it is being thrown when I'm simply instantiating a command class which is just a DTO.

This is the line that throws:
``` csharp
var command = new StartBulkIngestionCommand
{
	RequestDateTime = DateTimeOffset.Now,
	Reason = reason
};
```

And the contents of that class:
``` csharp
public class StartBulkIngestionCommand : ICommand
{
	public DateTimeOffset RequestDateTime { get; set; }

	public string Reason { get; set; }
}
```

Here's the stack trace:
```
> UJSTAFFORD [FTL 2017-08-10 09:45:44.139 -07:00] [Thread 17]  HITSystem.ArgumentNullException: Value cannot be null.
> Parameter name: property
>    at Serilog.Events.LogEvent.AddOrUpdateProperty(LogEventProperty property)
>    at Serilog.Events.LogEvent..ctor(DateTimeOffset timestamp, LogEventLevel level, Exception exception, MessageTemplate messageTemplate, IEnumerable`1 properties)
>    at SerilogExtensions.WriteInfo(ILogger logger, MessageTemplate messageTemplate, IEnumerable`1 properties) in C:\projects\nservicebus-serilog\NServiceBus.Serilog.Tracing\SagaAudit\SerilogExtensions.cs:line 16
>    at NServiceBus.Serilog.Tracing.SendMessageBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`1 next) in C:\projects\nservicebus-serilog\NServiceBus.Serilog.Tracing\MessageAudit\SendMessageBehavior.cs:line 34
>    at NServiceBus.ScheduleBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Scheduling\ScheduleBehavior.cs:line 21
>    at NServiceBus.ApplyTimeToBeReceivedBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Performance\TimeToBeReceived\ApplyTimeToBeReceivedBehavior.cs:line 26
>    at NServiceBus.DetermineMessageDurabilityBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Performance\MessageDurability\DetermineMessageDurabilityBehavior.cs:line 26
>    at NServiceBus.AddHostInfoHeadersBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Hosting\AddHostInfoHeadersBehavior.cs:line 23
>    at NServiceBus.AttachCorrelationIdBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Correlation\AttachCorrelationIdBehavior.cs:line 43
>    at NServiceBus.MutateOutgoingMessageBehavior.<InvokeOutgoingMessageMutators>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageMutators\MutateInstanceMessage\MutateOutgoingMessageBehavior.cs:line 52
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NServiceBus.UnicastSendRouterConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Routing\Routers\UnicastSendRouterConnector.cs:line 23
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at DAS.Services.Reviews.Command.Controllers.ReviewsController.<ForceIngestion>d__2.MoveNext() in C:\source\das\Platform\das.services.reviews\src\DAS.Services.Reviews.Command\Controllers\ReviewsController.cs:line 37
> UJSTAFFORD [FTL 2017-08-10 09:45:44.139 -07:00] [Thread 17]  HITSystem.ArgumentNullException: Value cannot be null.
> Parameter name: property
>    at Serilog.Events.LogEvent.AddOrUpdateProperty(LogEventProperty property)
>    at Serilog.Events.LogEvent..ctor(DateTimeOffset timestamp, LogEventLevel level, Exception exception, MessageTemplate messageTemplate, IEnumerable`1 properties)
>    at SerilogExtensions.WriteInfo(ILogger logger, MessageTemplate messageTemplate, IEnumerable`1 properties) in C:\projects\nservicebus-serilog\NServiceBus.Serilog.Tracing\SagaAudit\SerilogExtensions.cs:line 16
>    at NServiceBus.Serilog.Tracing.SendMessageBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`1 next) in C:\projects\nservicebus-serilog\NServiceBus.Serilog.Tracing\MessageAudit\SendMessageBehavior.cs:line 34
>    at NServiceBus.ScheduleBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Scheduling\ScheduleBehavior.cs:line 21
>    at NServiceBus.ApplyTimeToBeReceivedBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Performance\TimeToBeReceived\ApplyTimeToBeReceivedBehavior.cs:line 26
>    at NServiceBus.DetermineMessageDurabilityBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Performance\MessageDurability\DetermineMessageDurabilityBehavior.cs:line 26
>    at NServiceBus.AddHostInfoHeadersBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Hosting\AddHostInfoHeadersBehavior.cs:line 23
>    at NServiceBus.AttachCorrelationIdBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Correlation\AttachCorrelationIdBehavior.cs:line 43
>    at NServiceBus.MutateOutgoingMessageBehavior.<InvokeOutgoingMessageMutators>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageMutators\MutateInstanceMessage\MutateOutgoingMessageBehavior.cs:line 52
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NServiceBus.UnicastSendRouterConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Routing\Routers\UnicastSendRouterConnector.cs:line 23
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at DAS.Services.Reviews.Command.Controllers.ReviewsController.<ForceIngestion>d__2.MoveNext() in C:\source\das\Platform\das.services.reviews\src\DAS.Services.Reviews.Command\Controllers\ReviewsController.cs:line 37
```

**Comment by dasjestyr** [comment]
O_o so I just removed a sink from my logging configuration and now I'm getting more NSB errors on startup:

- Empty License string (although it is supplied in the NSB configuration
- The requested performance counter is not a custom counter, it has to be initialized as readonly

... this is starting to smell like more assembly scanning side effects... ?

**Comment by dasjestyr** [comment]
Ok this is probably on the wrong repo now, but I ditched NServiceBus.Host and converted to self hosted. I still got those two exceptions. I installed `NServiceBus.Metrics.PerformanceCounters.MsBuild` which got rid of the second exception, but it's still claiming that it's an empty license string.

**Comment by SimonCropp** [comment]
@dasjestyr just to qualify... you have fixed your logging issue and now only have the license problem, which we are dealing with on google groups? https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/VKSgQ9lQtog/efEMEehOAQAJ

BTW i think the logging location advice re the host is a little flawed and have raised and issue to track it  https://github.com/Particular/docs.particular.net/issues/3054

**Comment by SimonCropp** [comment]
> Ok this is probably on the wrong repo now

dont worry about it. we will clean up after you get everything working

**Comment by dasjestyr** [comment]
So it was fixed for a bit there until I upgraded it to netcoreapp and the exact same error is back now :| 

Using the 7.0 beta so I'm not sure if it was a regression (unlikely) ... but we weren't sure what the cause was to begin with 

> System.ArgumentNullException: Value cannot be null.
> Parameter name: property
>    at Serilog.Events.LogEvent.AddOrUpdateProperty(LogEventProperty property)
>    at Serilog.Events.LogEvent..ctor(DateTimeOffset timestamp, LogEventLevel level, Exception exception, MessageTemplate messageTemplate, IEnumerable`1 properties)
>    at SerilogExtensions.WriteInfo(ILogger logger, MessageTemplate messageTemplate, IEnumerable`1 properties)
>    at NServiceBus.Serilog.Tracing.SendMessageBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`1 next)
>    at NServiceBus.ScheduleBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Scheduling\ScheduleBehavior.cs:line 20
>    at NServiceBus.ApplyTimeToBeReceivedBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Performance\TimeToBeReceived\ApplyTimeToBeReceivedBehavior.cs:line 24
>    at NServiceBus.DetermineMessageDurabilityBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Performance\MessageDurability\DetermineMessageDurabilityBehavior.cs:line 26
>    at NServiceBus.AddHostInfoHeadersBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Hosting\AddHostInfoHeadersBehavior.cs:line 23
>    at NServiceBus.AttachCorrelationIdBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Correlation\AttachCorrelationIdBehavior.cs:line 38
>    at NServiceBus.AttachCausationHeadersBehavior.Invoke(IOutgoingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Causation\AttachCausationHeadersBehavior.cs:line 17
>    at NServiceBus.UnicastSendRouterConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Routing\Routers\UnicastSendRouterConnector.cs:line 23
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at DAS.Services.Reviews.Command.Controllers.ReviewsController.<ForceIngestion>d__2.MoveNext() in C:\source\das\Platform\das.services.reviews\src\DAS.Services.Reviews.Command\Controllers\ReviewsController.cs:line 43
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

**Comment by dasjestyr** [comment]
So I removed all Serilog -> NSB configuration and it's still throwing with NSB in the stack trace. Is this package doing some assembly scanning in the background to try and auto-wire this stuff up?

**Comment by SimonCropp** [comment]
can u try `endpointConfiguration.DisableFeature<TracingLog>();`

also it would be great if u could share a small repro

**Comment by dasjestyr** [comment]
I'll try putting together a repro that is shareable, or I can grant you readonly repo access. In the meanwhile, I removedNServiceBus.Serilog and the problem went away

**Comment by SimonCropp** [comment]
any update on that repro?

**Comment by dasjestyr** [comment]
We were forced to backburner that project so I haven't been in it for quite a while -- I've lost all context in the meanwhile D:  Other services seem to work just fine, so I have no complaints. I'll be sure to bring it back up if something like this starts happening again. Thanks for touching base

**Comment by SimonCropp** [comment]
kool thanks

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
