### ISSUE TITLE
Package on nuget relies on NSB version that isn't published yet (beta5)

### ISSUE THREAD

**Issue by janpieterz** [SimonCropp/NServiceBus.Serilog#4]
https://www.nuget.org/packages/NServiceBus.Serilog/3.0.0-beta0002
Refers to:
```
Dependencies
NServiceBus (>= 6.0.0-beta5 && < 7.0.0)
Serilog (>= 2.0.0)
```
While the last published version of NSB is beta4

**Comment by SimonCropp** [comment]
i pushed a new nuget. can u try that

**Comment by janpieterz** [comment]
Odd, works on one project (.net core classic .net), but on another one (4.6.1) it fails with, the error that it can't find NServiceBus.6.0.0-unstable0257 on nuget. I've checked and nowhere in the package that number even occurs. I'll have to dive in but this doesn't seem to be an issue with this one, cheers for the fix! :+1:

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
