### ISSUE TITLE
Upgrade Serilog to v2.0

### ISSUE THREAD

**Issue by mkrain** [SimonCropp/NServiceBus.Serilog#5]
Serilog has been updated to version 2.0 it would be awesome if this can do the same.

https://github.com/serilog/serilog/wiki/2.x-Upgrade-Guide

**Comment by mkrain** [comment]
I've updated the library here:

https://github.com/SimonCropp/NServiceBus.Serilog/pull/6

However, there are a few failing tests.  I'll need some guidance on why and if I need to fix them.  I noticed they failed prior to doing any work.

**Comment by mkrain** [comment]
I was hoping that the version of NServiceBus stayed < 6 as I haven't been able to move the newer versions.  Is there a way to get a package with Serilog >= 2 and NServiceBus.Core <= 5?

**Comment by SimonCropp** [comment]
@mkrain i pushed a new version to nuget that should work for u. can u confirm

and sorry for the delay

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
