### ISSUE TITLE
Strong named dll

### ISSUE THREAD

**Issue by tbandixen** [SimonCropp/NServiceBus.Serilog#7]
Hi,
Could you please sign your dll for strong named dll support?

Thanks and regards
 Thomas

**Comment by SimonCropp** [comment]
FYI i have some proposed change in the licensing model for NuGet packages under the NServiceBusExtensions Org https://discuss.particular.net/t/proposed-change-in-the-licensing-model-for-nuget-packages-under-the-nservicebusextensions-org
